### ISSUE TITLE
[bug?] policy log_prob should not be corrected

### ISSUE THREAD

**Issue by typoverflow** [hwang-ua/inac_pytorch#1]
Hi, 
thanks for sharing the code! After some reading I found a potential bug in your code:
https://github.com/hwang-ua/inac_pytorch/blob/af2508d1f25579430e4a4ac6a47b1eacdfd2d4f2/core/network/policy_factory.py#L64

You are actually not using tanh-squashed policies here, because the tanh is applied on `mu`, rather than on the sampled action. In this case the log-prob should not be corrected by `logp_pi -= (2*(np.log(2) - actions - F.softplus(-2*actions))).sum(axis=1)`. 

For the difference between SAC-like policies and the policies you used in InAC, you can have a look at the `SquashedGaussianActor` and `ClippedGaussianActor` in this file: https://github.com/typoverflow/OfflineRL-Lib/blob/master/offlinerllib/module/actor.py

Although after re-implementation I found that this does not affect the overall performance (see https://github.com/typoverflow/OfflineRL-Lib/blob/master/reproduce/benchmark_result.md), I think this still should be taken care of for rigorous comparison. Please correct me if there is any mis-understanding =)

**Comment by hwang-ua** [comment]
Hi! Thank you very much for capturing this! And thanks for checking the performance after the correction! We've updated our code to sample action from a normal distribution for a quick fix, will move to use squashed gaussian later.

**Comment by typoverflow** [comment]
Thanks for confirming! closing this issue.
