### ISSUE TITLE
Implementation details about Q update

### ISSUE THREAD

**Issue by linhlpv** [hwang-ua/inac_pytorch#2]
Hi @hwang-ua , thank for sharing the code.

I have read the paper and the implementation code and I found that there is different between the paper formulations and your implementation in Q value update. 
In the paper, as I see in Eq (16), you use learned value function to compute the value of the next state $s'$ and then update Q using the TD. 
![image](https://github.com/hwang-ua/inac_pytorch/assets/33130456/fcc78931-458e-4346-b370-6bd654547ac7)
But in your implementation [line 122, 123](https://github.com/hwang-ua/inac_pytorch/blob/main/core/agent/in_sample.py#L123) 
```
    def compute_loss_q(self, data):
        states, actions, rewards, next_states, dones = data['obs'], data['act'], data['reward'], data['obs2'], data['done']
        with torch.no_grad():
            next_actions, log_probs = self.ac.pi(next_states)
        min_Q, _, _ = self.get_q_value_target(next_states, next_actions)
        q_target = rewards + self.gamma * (1 - dones) * (min_Q - self.tau * log_probs)
    
        minq, q1, q2 = self.get_q_value(states, actions, with_grad=True)
    
        critic1_loss = (0.5 * (q_target - q1) ** 2).mean()
        critic2_loss = (0.5 * (q_target - q2) ** 2).mean()
        loss_q = (critic1_loss + critic2_loss) * 0.5
        q_info = minq.detach().numpy()
        return loss_q, q_info
```
you just compute the target using the Q_target not V_function. 
I'm curious about this specific choice and this difference. Could you explain why the choice was made? 
Thank you so much.
Best,
Linh

**Comment by hwang-ua** [comment]
Hi Linh, Thank you for being interested in our work! In practice we followed the update in SAC (please see [spinning up](https://spinningup.openai.com/en/latest/algorithms/sac.html) and [eq 7~9 in the paper](https://arxiv.org/pdf/1801.01290.pdf)). As in your screenshot, the expectation of $\min_{i=1,2} Q_i - \tau \log \pi$ under policy $\pi$ is the target of V.

**Comment by linhlpv** [comment]
Hi @hwang-ua , thank you for your answer!
